#!/usr/bin/env python
# -*- coding: utf-8 -*-

import requests
from jinja2 import Template

#We will create our own GitHub interface because existing libraries 
#don't support what we want.

class GithubClient:
	def __init__(self, username, password, baseurl="https://api.github.com"):
		self.username = username
		self.password = password
		self.baseurl = baseurl
	def create_issue(self, title, body, owner, repo):
		#TODO: confirm enterprise github support
		request_url = '%s/repos/%s/%s/issues' % (self.baseurl, owner, repo)
		request_payload = {
			"title": title,
			"body": body,
		}
		print request_url
		r = requests.post(request_url, 
			auth=(self.username, self.password),
			json=request_payload
		)
		return r.json()
	@staticmethod
	def create_issue_body(commit_body):
		template_str = "Autogenerated commit via ShipShit. Commit {{commit_sha}}: '{{commit_text}}'"
		return Template(template_str).render(commit_sha=commit_body["id"], commit_text=commit_body["message"])
